import {marketFreshness,graphAddress,safeUrl,validAddress,money,short,when,selectRows} from './utils.mjs';
const $=s=>document.querySelector(s);const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
const state={page:'Radar',mode:'Markets',query:'',sort:'volume',watchOnly:false,snapshot:null,busy:false,watchlist:[],detail:null,detailRequest:0};try{const stored=JSON.parse(localStorage.getItem('trenchnet-watchlist')||'[]');state.watchlist=Array.isArray(stored)?stored.filter(validAddress):[];}catch{}
function button(text,fn,cls){const b=el('button',text,cls);b.type='button';b.addEventListener('click',fn);return b;}
function link(text,url){const safe=safeUrl(url);if(!safe)return el('span','Receipt unavailable','muted');const a=el('a',text,'receipt');a.href=safe;a.target='_blank';a.rel='noopener noreferrer';return a;}
function empty(title,text){const e=el('div',undefined,'empty');e.append(el('span','⌁','empty-symbol'),el('h3',title),el('p',text));return e;}
function watch(address){state.watchlist=state.watchlist.includes(address)?state.watchlist.filter(x=>x!==address):[...state.watchlist,address];try{localStorage.setItem('trenchnet-watchlist',JSON.stringify(state.watchlist));}catch{$('#feedback').textContent='Local storage is unavailable. Your watchlist is kept for this session.';}render();}
function watchButton(address){const saved=state.watchlist.includes(address);const b=button(saved?'★':'☆',()=>watch(address),'watch'+(saved?' saved':''));b.setAttribute('aria-label',(saved?'Remove from':'Add to')+' watchlist '+short(address));b.setAttribute('aria-pressed',String(saved));return b;}
function tokenName(address){const m=state.snapshot?.markets.find(x=>x.address===address);return m?.symbol||short(address);}
function table(headers,rows){const wrap=el('div',undefined,'table-wrap');const t=el('table'),head=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const body=el('tbody');rows.forEach(r=>body.append(r));t.append(body);wrap.append(t);return wrap;}
function cell(value,cls){const td=el('td',undefined,cls);td.append(value instanceof Node?value:el('span',value));return td;}
function nameButton(address,name,sub,kind='token'){const b=button(name,()=>detail(kind,address),'token-button');if(sub)b.append(el('small',sub));return b;}
function marketRow(m,i){const tr=el('tr');tr.title='Quote as of '+when(m.fetchedAt)+' · '+marketFreshness(m);const token=el('div',undefined,'token-cell');token.append(el('span',(m.symbol||'?').slice(0,2).toUpperCase(),'token-icon'),nameButton(m.address,m.symbol||short(m.address),m.name||short(m.address)));const change=m.change24h==null?'—':(Number(m.change24h)>0?'+':'')+Number(m.change24h).toFixed(2)+'%';tr.append(cell(String(i+1).padStart(2,'0'),'rank'),cell(token),cell(priceCell(m),'num'),cell(change,'num '+(Number(m.change24h)<0?'down':'up')),cell(money(m.marketCap),'num'),cell(money(m.volume24h),'num'),cell(money(m.liquidityUsd),'num'),cell(watchButton(m.address)));tr.addEventListener('click',e=>{if(!e.target.closest('button,a'))detail('token',m.address);});return tr;}
function priceCell(m){const box=el('span',undefined,'price-cell');box.append(el('span',money(m.priceUsd)),el('small',marketFreshness(m)==='recent'?'As of '+when(m.fetchedAt):marketFreshness(m).toUpperCase()+' · '+when(m.fetchedAt),marketFreshness(m)==='stale'?'down':'muted'));return box;}
function tradeRow(t){const tr=el('tr');tr.append(cell(el('span',t.side==='sell'?'SELL':'BUY','badge '+(t.side==='sell'?'sell':''))),cell(nameButton(t.mint,tokenName(t.mint),short(t.mint))),cell(nameButton(t.wallet,short(t.wallet),'Observed wallet','wallet')),cell(t.solAmount==null?'—':Number(t.solAmount).toLocaleString('en-US',{maximumFractionDigits:4})+' SOL','num'),cell(when(t.timestamp),'num'),cell(link('Transaction ↗',t.explorerUrl)));return tr;}
function renderRadar(){const s=state.snapshot;const rows=selectRows(s,state);$('#filter-note').textContent={Markets:'DexScreener boosted listings · not wallet signals',Signals:'All observed buys and sells',Fresh:'Observed buys only · not new-token listings',Exits:'Observed sells only'}[state.mode];if(!rows.length){$('#content').append(empty(state.mode==='Markets'?'No matching markets':'No matching observed trades',state.query||state.watchOnly?'Try a different search or turn off the watchlist filter.':'Nothing is being inferred. This view fills only when the collector records public evidence.'));return;}$('#content').append(state.mode==='Markets'?table(['#','Token','Price','24h','Market cap','Volume / 24h','Liquidity','Watch'],rows.map(marketRow)):table(['Side','Token','Wallet','Amount','Observed at','Receipt'],rows.map(tradeRow)));}
function renderTraders(){const rows=state.snapshot.traders;if(!rows.length){$('#content').append(empty('No wallets observed yet','Wallets appear after a qualifying trade is collected. Market listings alone do not identify traders.'));return;}$('#content').append(table(['#','Observed wallet','Buys','Sells','Tokens','Last seen','Sample summary'],rows.map((w,i)=>{const tr=el('tr');tr.append(cell(String(i+1).padStart(2,'0'),'rank'),cell(nameButton(w.address,short(w.address),'Inspect activity →','wallet')),cell(w.buys,'num'),cell(w.sells,'num'),cell(w.tokens,'num'),cell(when(w.lastSeen),'num'),cell(w.summary||'Retained observations only','muted'));return tr;})));}
function evidenceLinks(ids,target){(ids||[]).forEach((id,i)=>{const trade=state.snapshot?.trades.find(t=>t.id===id);target.append(trade?link('Evidence '+(i+1)+' ↗',trade.explorerUrl):el('span','Evidence outside snapshot: '+short(id),'muted'));});}
function outcomeView(outcome){const section=el('section',undefined,'outcome');section.append(el('h4','What happened next · 1h observed window'));if(outcome?.status==='observed'){section.append(el('p',outcome.summary||'Later activity recorded in the retained sample.'),metrics([['LATER BUYS',outcome.buys??'—'],['LATER SELLS',outcome.sells??'—'],['OBSERVED WALLETS',outcome.wallets??'—']]));const receipts=el('div',undefined,'actions');evidenceLinks(outcome.evidence,receipts);section.append(receipts);}else section.append(el('p','Pending · No observed later records in the retained sample. This is not evidence of zero activity.'));return section;}
function relationships(rows){const section=el('section',undefined,'relationships');section.append(el('h3','Repeated co-buy pairs'),el('p','Shared asset ≠ human coordination. These pairs reflect recorded buys, not identity, ownership or intent.','coverage'));if(!rows.length)section.append(empty('No repeated co-buy pairs observed','The retained sample has no qualifying repeated shared-token buys. This does not establish that wallets are unrelated.'));rows.forEach(r=>{const row=el('article',undefined,'relationship-entry method-card');const wallets=el('div',undefined,'actions');(r.wallets||[]).forEach(address=>wallets.append(nameButton(address,short(address),'Observed wallet','wallet')));row.append(wallets,el('p',String(r.sharedTokenCount??r.sharedTokens?.length??0)+' shared tokens'));const tokens=el('div',undefined,'actions');(r.sharedTokens||[]).forEach(mint=>tokens.append(nameButton(mint,tokenName(mint),short(mint))));const receipts=el('div',undefined,'actions');evidenceLinks(r.evidence,receipts);row.append(tokens,receipts);section.append(row);});$('#content').append(section);}
function journal(decisions,target){if(!decisions.length){target.append(empty('No decisions without evidence','The journal records deterministic rules triggered by observed trades. No AI verdicts are generated.'));return;}decisions.forEach(d=>{const row=el('article',undefined,'journal-entry'),body=el('div',undefined,'body');body.append(nameButton(d.mint,tokenName(d.mint)),el('p',d.summary));const receipts=el('div',undefined,'actions');(d.evidence||[]).forEach((id,i)=>{const t=state.snapshot.trades.find(x=>x.id===id);if(t)receipts.append(link('Evidence '+(i+1)+' ↗',t.explorerUrl));else receipts.append(el('span','Evidence outside snapshot: '+short(id),'muted'));});body.append(receipts,el('span','RULES / '+d.rulesVersion,'label'),outcomeView(d.outcome));row.append(el('span',String(d.kind).replaceAll('_',' '),'badge'),body,el('time',when(d.timestamp)));target.append(row);});}
function network(){const {nodes=[],edges=[],relationships:pairs=[]}=state.snapshot.graph||{};relationships(pairs);if(!nodes.length){$('#content').append(empty('Connections need a trail','The network connects observed wallets to tokens they traded. No connections are invented from market data.'));return;}const layout=el('div',undefined,'network-layout'),stage=el('div',undefined,'graph-stage'),legend=el('div',undefined,'graph-legend');const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 700 360');svg.setAttribute('aria-label','Observed wallet-token connections');const shown=nodes.slice(0,36),positions=new Map(shown.map((n,i)=>[n.id,{x:350+260*Math.cos(i*2*Math.PI/shown.length),y:180+125*Math.sin(i*2*Math.PI/shown.length)}]));edges.forEach(e=>{const a=positions.get(e.source),b=positions.get(e.target);if(!a||!b)return;const l=document.createElementNS(ns,'line');Object.entries({x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:'#375e44','stroke-width':1}).forEach(([k,v])=>l.setAttribute(k,v));svg.append(l);});shown.forEach(n=>{const p=positions.get(n.id),g=document.createElementNS(ns,'g');g.classList.add('graph-node');g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',n.type+' '+n.id);g.addEventListener('click',()=>detail(n.type,graphAddress(n)));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();detail(n.type,graphAddress(n));}});const c=document.createElementNS(ns,'circle');Object.entries({cx:p.x,cy:p.y,r:n.type==='token'?10:6,fill:n.type==='token'?'#b7ffcd':'#122719',stroke:'#b7ffcd'}).forEach(([k,v])=>c.setAttribute(k,v));const t=document.createElementNS(ns,'text');t.setAttribute('x',p.x);t.setAttribute('y',p.y-17);t.setAttribute('text-anchor','middle');t.textContent=String(n.label||short(n.id)).slice(0,14);g.append(c,t);svg.append(g);legend.append(button((n.type==='token'?'◇ ':'○ ')+(n.label||short(n.id)),()=>detail(n.type,graphAddress(n))));});stage.append(svg);legend.prepend(el('p','SELECT A WALLET OR TOKEN','label'));layout.append(stage,legend);$('#content').append(layout,el('p',`Showing ${shown.length} of ${nodes.length} observed nodes. Lines represent recorded wallet–token activity, not ownership or coordinated intent.`,'coverage'));}
function method(){const c=$('#content');const grid=el('div',undefined,'method-grid');[['01 / OBSERVE','Public trail. Bounded view.','Market metadata comes from public providers. Wallet activity appears only when the collector observes qualifying trade receipts. Collection is bounded: this is not a wallet’s full history.'],['02 / CONNECT','Rules, not predictions.','First-seen activity, shared token buys and observed sells can trigger deterministic journal entries. Every entry links to evidence. A shared token does not establish coordinated ownership.'],['03 / VERIFY','Receipts over reputation.','Inspect the original transaction before drawing conclusions. PnL and trader profitability are unavailable without complete cost basis and transaction history. This app does not sign or execute trades.']].forEach(([n,h,p])=>{const a=el('article',undefined,'method-card');a.append(el('span',n,'eyebrow'),el('h3',h),el('p',p));grid.append(a);});const analysis=el('div',undefined,'model-row');analysis.append(el('span','ENGINE / DETERMINISTIC ON-CHAIN RULES V2'),el('span','NO INFERENCE API'),el('span','NO PAID MODELS'));c.append(grid,analysis,el('p','Your watchlist is stored only in this browser. Snapshot export contains the public data currently available. No wallet connection, private keys, or paid trading actions.','coverage'));}
function render(){const s=state.snapshot;$('#watch-count').textContent=state.watchlist.length;$('#watch-filter').setAttribute('aria-pressed',String(state.watchOnly));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$('#radar-controls').hidden=state.page!=='Radar';$('#section-kicker').textContent=({Radar:'01 / THE RADAR',Traders:'02 / PUBLIC ACTIVITY',Network:'03 / FOLLOW THE CONNECTIONS',Journal:'04 / EVIDENCE LOG',Method:'05 / UNDER THE HOOD'})[state.page];$('#page-title').textContent=({Radar:'A clearer view of the trenches.',Traders:'Observed wallets',Network:'The transaction network',Journal:'The decision journal',Method:'Evidence first. Always.'})[state.page];$('#counts').replaceChildren();if(s){$('#counts').append(el('span',s.markets.length+' MARKETS'),el('span',s.trades.length+' TRADES'));}$('#content').replaceChildren();if(state.page==='Method'){method();return;}if(!s){$('#content').append(empty('The collector is not reachable','Use Refresh to try again. No sample data is shown.'));return;}if(state.page==='Radar')renderRadar();else if(state.page==='Traders')renderTraders();else if(state.page==='Network')network();else journal(s.decisions,$('#content'));}
async function fetchJSON(url){const r=await fetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(25000)});let data;try{data=await r.json();}catch{throw Error('The data service returned an invalid response.');}if(!r.ok)throw Error(data.error||'Data request failed ('+r.status+').');return data;}
async function refresh(){if(state.busy)return;state.busy=true;$('#refresh').disabled=true;$('#refresh').textContent='Reading…';try{const s=await fetchJSON('/api/snapshot');if(!Array.isArray(s.markets)||!Array.isArray(s.trades))throw Error('Snapshot format is unavailable.');state.snapshot={...s,traders:s.traders||[],decisions:s.decisions||[]};$('#status-text').textContent=({ok:'Public observations available',partial:'Partial collection · showing retained observations',error:'Source unavailable · showing retained observations',starting:'Waiting for public observations'})[s.status?.collector]||'Public snapshot available';$('#status-text').title=s.status?.message||'';$('#status-dot').className=s.status?.collector||'partial';$('#updated').textContent='LAST CHECK '+when(s.updatedAt);$('#coverage').textContent=s.status?.coverage||'Collection is bounded. Market data is not proof of wallet activity.';render();}catch(e){$('#status-text').textContent=(state.snapshot?'Showing last snapshot. ':'')+e.message;$('#status-dot').className='error';if(!state.snapshot)render();}finally{state.busy=false;$('#refresh').disabled=false;$('#refresh').textContent='Refresh ↻';}}
function metrics(items){const g=el('div',undefined,'metric-grid');items.forEach(([label,value])=>{const m=el('div',undefined,'metric');m.append(el('span',label,'label'),el('strong',value));g.append(m);});return g;}
function tradeList(trades,target){if(!trades.length){target.append(empty('No observed trades','No qualifying wallet activity is available for this address in the current collection window.'));return;}trades.forEach(t=>{const row=el('div',undefined,'trade-item'),body=el('div',undefined,'body');body.append(nameButton(t.wallet,short(t.wallet),null,'wallet'),el('p',tokenName(t.mint)+' · '+when(t.timestamp)),el('span',t.verified?'Receipt verified':'Verification not established','label'));row.append(el('span',t.side==='sell'?'SELL':'BUY','badge '+(t.side==='sell'?'sell':'')),body,link('Receipt ↗',t.explorerUrl));target.append(row);});}
async function detail(kind,address){if(!validAddress(address)){$('#feedback').textContent='Enter a valid Solana token address to inspect.';return;}state.detail={kind,address};const request=++state.detailRequest;const box=$('#detail-content');box.replaceChildren(el('h2','Loading dossier…'));box.firstChild.id='detail-title';if(!$('#detail').open)$('#detail').showModal();try{const d=await fetchJSON('/api/'+(kind==='wallet'?'wallet':'token')+'?address='+encodeURIComponent(address));if(request!==state.detailRequest)return;box.replaceChildren();const title=el('h2',kind==='wallet'?'Observed wallet':d.market?.symbol||'Token dossier');title.id='detail-title';box.append(title,el('p',address,'address'));const actions=el('div',undefined,'actions');actions.append(button('Copy address',async e=>{const target=e.currentTarget;try{await navigator.clipboard.writeText(address);target.textContent='Copied';}catch{const range=document.createRange();range.selectNodeContents(box.querySelector('.address'));getSelection().removeAllRanges();getSelection().addRange(range);}}));if(kind!=='wallet')actions.append(button(state.watchlist.includes(address)?'★ Remove watch':'☆ Watch token',e=>{watch(address);e.currentTarget.textContent=state.watchlist.includes(address)?'★ Remove watch':'☆ Watch token';}));actions.append(link('Solscan ↗','https://solscan.io/'+(kind==='wallet'?'account/':'token/')+address));if(d.market?.pairUrl)actions.append(link('Market ↗',d.market.pairUrl));box.append(actions);if(kind==='wallet')box.append(el('p',d.profile?.summary||'No wallet summary available in this retained sample.','wallet-summary'),metrics([['OBSERVED BUYS',d.profile?.buys??'—'],['OBSERVED SELLS',d.profile?.sells??'—'],['FIRST SEEN',when(d.profile?.firstSeen)],['LAST SEEN',when(d.profile?.lastSeen)],['OBSERVED SOL BOUGHT',d.profile?.observedSolBought??'—'],['OBSERVED SOL SOLD',d.profile?.observedSolSold??'—']]),el('p','SOL amounts are observed trade flow in a retained sample, not profit or a complete wallet history.','coverage'));else box.append(metrics([['PRICE',money(d.market?.priceUsd)],['MARKET CAP',money(d.market?.marketCap)],['LIQUIDITY',money(d.market?.liquidityUsd)]]));if(d.market)box.append(el('p','Price as of '+when(d.market.fetchedAt)+' · '+marketFreshness(d.market),'coverage'));box.append(el('p',d.coverage||'Bounded observations. Full history and cost basis are unavailable.','coverage'));if(d.error)box.append(el('p',d.error,'feedback'));box.append(el('h3','Observed activity'));tradeList(d.trades||[],box);}catch(e){if(request!==state.detailRequest)return;box.replaceChildren();const h=el('h2','Dossier unavailable');h.id='detail-title';box.append(h,el('p',e.message,'coverage'),button('Try again',()=>detail(kind,address)));}}
$('#close-detail').addEventListener('click',()=>$('#detail').close());$('#detail').addEventListener('close',()=>{state.detail=null;state.detailRequest++;});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{state.page=b.dataset.page;$('#feedback').textContent='';render();}));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;render();}));$('#search').addEventListener('input',e=>{state.query=e.target.value.trim();$('#feedback').textContent='';render();});$('#search-form').addEventListener('submit',e=>{e.preventDefault();detail('token',$('#search').value.trim());});$('#watch-filter').addEventListener('click',()=>{state.watchOnly=!state.watchOnly;render();});$('#sort').addEventListener('change',e=>{state.sort=e.target.value;render();});$('#refresh').addEventListener('click',refresh);setInterval(()=>{if(!document.hidden)refresh();},90000);refresh();

// Decorative motion only. No market values or trading activity are synthesized.
function initAmbientMotion(){
 const hero=document.querySelector('.hero'),panel=document.querySelector('.schematic');
 if(!hero||!panel)return;
 const rain=document.createElement('canvas'),net=document.createElement('canvas');
 rain.className='matrix-rain';net.className='network-motion';
 for(const c of [rain,net])c.setAttribute('aria-hidden','true');
 hero.prepend(rain);panel.querySelector('svg').after(net);
 const rc=rain.getContext('2d'),nc=net.getContext('2d');if(!rc||!nc){rain.remove();net.remove();return;}
 hero.classList.add('motion-ready');
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let visible=true,frame=0,last=0,time=0,rw=0,rh=0,nw=0,nh=0;
 const chars='01{}<>/ABCDEF:;';
 const nodes=Array.from({length:34},(_,i)=>({angle:i*2.39996,r:0.2+((i*17)%29)/40,phase:i*1.71}));
 function size(c){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);c.getContext('2d').setTransform(d,0,0,d,0,0);return [r.width,r.height];}
 function resize(){[rw,rh]=size(rain);[nw,nh]=size(net);draw();}
 function draw(){
  rc.clearRect(0,0,rw,rh);rc.font='11px monospace';
  for(let x=12,col=0;x<rw;x+=23,col++){
   const speed=22+(col*13%38),head=((time*speed+col*137)%(rh+280))-40;
   for(let k=0;k<17;k++){
    const y=head-k*15;if(y<0||y>rh)continue;
    rc.fillStyle=k===0?'rgba(155,255,198,.6)':`rgba(0,255,125,${(1-k/17)*.34})`;
    rc.fillText(chars[(col*7+k*3+Math.floor(time*2))%chars.length],x,y);
   }
  }
  nc.clearRect(0,0,nw,nh);const cx=nw/2,cy=nh/2,scale=Math.min(nw,nh)*.48;
  nc.strokeStyle='#143629';nc.lineWidth=.6;
  for(let r of [.38,.7,1]){nc.beginPath();nc.ellipse(cx,cy,scale*r,scale*r*.78,0,0,Math.PI*2);nc.stroke();}
  const pos=nodes.map(n=>{const a=n.angle+time*.045;return [cx+Math.cos(a)*n.r*scale,cy+Math.sin(a)*n.r*scale*.79+Math.sin(time*.35+n.phase)*7];});
  pos.forEach((p,i)=>{
   const q=pos[(i+7)%pos.length];
   nc.strokeStyle=i%3?'rgba(0,255,133,.16)':'rgba(179,138,255,.3)';nc.beginPath();nc.moveTo(...p);nc.lineTo(...q);nc.stroke();
   if(i%3===0){const f=(time*.22+i*.13)%1;nc.fillStyle=i%2?'#b38aff':'#80ffbc';nc.beginPath();nc.arc(p[0]+(q[0]-p[0])*f,p[1]+(q[1]-p[1])*f,1.8,0,Math.PI*2);nc.fill();}
   nc.fillStyle=i%7===0?'#b38aff':'#00e980';nc.beginPath();nc.arc(...p,i%7===0?3.5:1.6,0,Math.PI*2);nc.fill();
  });
  nc.strokeStyle='#00ff85';nc.lineWidth=1;nc.strokeRect(cx-14,cy-14,28,28);
  nc.fillStyle='#020b07';nc.fillRect(cx-13,cy-13,26,26);nc.fillStyle='#d3ffe3';nc.font='11px monospace';nc.textAlign='center';nc.fillText('TN',cx,cy+4);
  nc.font='8px monospace';nc.fillStyle='#719483';nc.fillText('WALLETS / TOKENS / CONNECTIONS',cx,nh-13);
  rain.dataset.frame=String(Math.round(time*30));net.dataset.frame=rain.dataset.frame;
 }
 function tick(now){frame=0;if(document.hidden||!visible||reduced.matches)return;if(now-last>=33){time+=last?Math.min((now-last)/1000,.1):.033;last=now;draw();}frame=requestAnimationFrame(tick);}
 function sync(){cancelAnimationFrame(frame);frame=0;last=0;hero.classList.toggle('motion-paused',document.hidden||!visible||reduced.matches);if(!document.hidden&&visible&&!reduced.matches)frame=requestAnimationFrame(tick);else draw();}
 new ResizeObserver(resize).observe(hero);
 new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;sync();},{rootMargin:'80px'}).observe(hero);
 document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);
 resize();sync();
}
initAmbientMotion();
